version: 2
jobs:
  build:
    docker:
    - image: golang:1.11.5
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build and push Docker image
        command: |
          docker build -t mobingi/oceand:${CIRCLE_SHA1} .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push mobingi/oceand:${CIRCLE_SHA1}
