apiVersion: v1
kind: ServiceAccount
metadata:
  name: oceand
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oceand
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - deployments
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oceand
roleRef:
  kind: Role
  name: oceand
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: oceand
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oceand
  namespace: kube-system
data: 
  config.yaml: |-
    id: rootuser-subuser
    token: token
    templateName: templateName
    clusterName: clusterName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceand
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: oceand
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: oceand
    spec:
      serviceAccountName: oceand
      containers:
      - name: oceand
        image: n1ce37/oceand:v1
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: oceand
          mountPath: /etc/oceand/config
      volumes:
        - name: oceand
          configMap:
            name: oceand