apiVersion: v1
kind: ServiceAccount
metadata:
  name: oceand
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oceand
  #labels:
    #kubernetes.io/cluster-service: "true"
    #addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - pods
  - services
  - deployments
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oceand
roleRef:
  kind: ClusterRole
  name: oceand
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: oceand
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oceand
  namespace: kube-system
data: 
  config.yaml: |-
    id: rootuser-subuser
    token: token
    templateName: templateName
    clusterName: clusterName
---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all
#spec:
#  podSelector: {}
#  egress:
#  - {}
#  policyTypes:
#  - Egress
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceand
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: oceand
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: oceand
    spec:
      serviceAccountName: oceand
      containers:
      - name: oceand
        image: n1ce37/oceand:latest
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/oceand/config
      volumes:
        - name: config-volume
          configMap:
            name: oceand